### ISSUE TITLE
OkHttp拦截器获取GET/POST请求参数并添加公共参数 - Pig Cat | YSY

### ISSUE THREAD

**Issue by ysy950803** [ysy950803/ysy950803.github.io#9]
https://blog.ysy950803.top/2019/07/05/OkHttp%E6%8B%A6%E6%88%AA%E5%99%A8%E8%8E%B7%E5%8F%96GET-POST%E8%AF%B7%E6%B1%82%E5%8F%82%E6%95%B0%E5%B9%B6%E6%B7%BB%E5%8A%A0%E5%85%AC%E5%85%B1%E5%8F%82%E6%95%B0/ 

 Full-Stack, Android, AI

**Comment by PascalTang** [comment]
請問下
我都會400 error是啥原因
